config/routes.rb
Rails.application.routes.draw do
 
  get 'oauth/instagram/connect', to: 'sessions#new'
  get 'oauth/instagram/callback', to: 'sessions#create'

  resources :artifacts
  resources :users, only: [:new, :create, :destroy]

  root :to => 'artifacts#index'

end

app/models/artifact.rb
class Artifact < ActiveRecord::Base

  validates :title, presence: true
  validates :country, presence: true
  validates :city, presence: true

  scope :by_query, ->(query) { where( "title LIKE :q OR artist LIKE :q", q: "%#{query}" ) }
  scope :by_city_or_country, ->(city, country) { where( "city = ? OR country = ?", city, country ) }

  def self.search(query, city, country)
    full_query = Artifact
    full_query = full_query.by_query(query) if query.present?
    full_query = full_query.by_city_or_country(city, country) if city.present? || country.present?
    return full_query
  end

  def self.unique_by_city
    self.select(:city).distinct
  end

  def self.unique_by_country
    self.select(:country).distinct
  end

  def image_url
    remote_image_url
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

app/controllers/artifacts_controller.rb
class ArtifactsController < ApplicationController

  def index
    @artifact = Artifact.new
    if params[:query] || params[:city] || params[:country]
      @artifacts = Artifact.search(params[:query], params[:city], params[:country]).all
    else
      @artifacts = Artifact.all.order('random()')
    end
  end

  def show
    @artifact = Artifact.find(params[:id])
  end

  def create
    @artifact = Artifact.new(artifact_params)

    if @artifact.save
      redirect_to artifacts_path
    else
      render :new
    end
  end

  def edit
    @artifact = Artifact.find(params[:id])
  end

  def update
    @artifact = Artifact.find(params[:id])

    if @artifact.update_attributes(artifact_params)
      redirect_to artifact_path(@artifact)
    else
      render :edit
    end
  end


  protected

  def artifact_params
    params.require(:artifact).permit(
      :title, :artist, :country, :city, :description, :image, :remote_image_url
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artifacts_helper.rb
module ArtifactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/artifacts/_artifact.html.erb
<div class="brick">
  
  <%= image_tag artifact.image_url.to_s, :class => "img" %>
  
  <p class="img-title"><%= artifact.title %></p>
  
  <p class="img-location"><%= artifact.city + ", " + artifact.country%></p>
  
</div> 

app/views/artifacts/_form.html.erb
<%= form_for @artifact do |f| %>

<div class="submit-art">
  <% if @artifact.errors.any? %>
      <%= pluralize(@artifact.errors.count, "error") %> prevented this artwork from being submitted:
      <ul>
        <% @artifact.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
  <% end %>

  <div class="form-item">
    <%= f.label "title" %>
    <%= f.text_field "title" %>
  </div>
  <div>
    <p class="non-animated-label">Country</p>
    <%= f.country_select :country, priority_countries: ["CA", "US"] %>
    <%= puts params %>
  </div>
  <div class="form-item">
    <%= f.label "city" %>
    <%= f.text_field "city" %>
  </div>
  <div class="form-item">
    <%= f.label "artist" %>
    <%= f.text_field "artist" %>
  </div>
  <div>
    <p class="non-animated-label">Upload Image</p>
    <p class="image-uploader"><%= f.file_field :image, class: "image-uploader-input" %></p>
  </div>
  <div class="form-item">
    <%= f.label :remote_image_url, "Image Link" %>
    <%= f.text_field :remote_image_url %>
  </div>
  <div>
    <%= f.submit "Submit", class: "btn" %>
  </div>
<div>

<% end %>    

app/views/artifacts/edit.html.erb
<%= link_to "Back to artwork", artifacts_path %>

<h2>Edit this artwork</h2>

<%= render 'form' %>

app/views/artifacts/index.html.erb
<div class="top-bar">
  <nav class="nav">
    <a href="/" id="logo">artfully</a>
    <div class="search-icon">
      <span class="glyphicon glyphicon-search" style="color: #38cfd6;"></span>
    <div>
  </nav>

  <div class="search-bar">
  <%= form_tag artifacts_path(anchor: "photo_wall"), method: :get do %>
    <span class="glyphicon glyphicon-search" style="color: #38cfd6;"></span>
    <%= text_field_tag :query, params[:query], placeholder: "search by artist or title"%>
    <%= select_tag :city, options_from_collection_for_select(Artifact.unique_by_city, :city, 'city'), prompt: "- select a city -", class: "query-select-box" %>
    <%= select_tag :country, options_from_collection_for_select(Artifact.unique_by_country, :country, 'country'), prompt: "- select a country -", class: "query-select-box" %>
    <%= submit_tag "SEARCH", :name => nil, class: "search-btn" %>
  <% end %>
  </div>
</div>


<div class="hero-img">
  <div class="hero-box">
    <div class="hero-txt">
      artfully is a collection of public art around the globe curated by art lovers like you. Whether it's a sidewalk mural or commissioned sculpture, join the movement to index the world's art by sharing your artful encounters on artfully today.
    </div>
    <%= link_to "Submit Art", "#", {:class => "btn", 'data-toggle' =>  "modal", 'data-target' => '#modal-window'} %>
  </div>
</div>


<a name="photo_wall"><div id="freewall" class="free-wall">
  <%= render @artifacts %>
</div></a>

<div class="modal fade" id="modal-window" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-center">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Submit New Artwork</h4>
      </div>
      <div class="modal-body">
      <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/artifacts/new.html.erb
<%= render 'form' %>

app/views/artifacts/show.html.erb
<%= link_to "Back to all artwork", artifacts_path %>

<%= @artifact.title %> (<%= link_to "edit", edit_artifact_path(@artifact) %>)
<%= @artifact.city %>, <%= @artifact.country %>
<%= @artifact.artist %>
<%= @artifact.description %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>artfully</title>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="../assets/javascript/freewall.js"></script>
    
    <link href='http://fonts.googleapis.com/css?family=Quicksand:300,400,700|Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  </head>
  
  <body>
    <%= yield %>
  </body>

</html>